### YAML Template.
#---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb?useLegacyDatetimeCode=false&serverTimezone=Asia/Manila
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
server:
  port: 8060